//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geta.CacheManager.Admin {
    
    
    public partial class Default {
        
        /// <summary>
        /// Menu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Shell.Web.UI.WebControls.ShellMenu Menu;
        
        /// <summary>
        /// DynamicTable2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.UI.WebControls.DynamicTable DynamicTable2;
        
        /// <summary>
        /// DynamicRow3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.UI.WebControls.DynamicRow DynamicRow3;
        
        /// <summary>
        /// DynamicCell5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.UI.WebControls.DynamicCell DynamicCell5;
        
        /// <summary>
        /// DynamicRow4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.UI.WebControls.DynamicRow DynamicRow4;
        
        /// <summary>
        /// Dynamiccell6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.UI.WebControls.DynamicCell Dynamiccell6;
        
        /// <summary>
        /// InfoFrame control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.UI.WebControls.SystemIFrame InfoFrame;
    }
}
